### ISSUE TITLE
Login page – Missing date modified and change button position

### ISSUE THREAD

**Issue by hydegeoff** [mmiron-HC/WST-RSAMS#22]
Problem:
1.	The button is touching footer background.  TBS guidelines does not specifically mention this as being a problem, but it does not have any items touching top part of the footer’s background image.  See screenshot.
2.	There is no version number or data modified on the login page.  It is classified as a transaction page under TBS guidelines:  Go here for more information: https://design.canada.ca/common-design-patterns/site-footer.html

Expected Result:

Add version or date modified to login page and add a line space after the login button in accordance with TBS Guidelines

URL: https://hcdev.openplus.ca/en/user/login
User Agent:  Chrome (Version 92.0.4515.107 (Official Build) (64-bit)); Firefox (90.0.2 (64-bit));
Language: EN and FR

Steps to reproduce: 
1.	Enter login info (hcdev/hc) into pop-up screen to access environment
2.	View the login page as shown in screen shot.
![Login - date modified missing and wrong button position](https://user-images.githubusercontent.com/88147013/127701148-991409ae-d591-4c8e-b778-caadf0b0fe0f.jpg)

**Comment by mmiron-HC** [comment]
Please apply across the application.

**Comment by davidgotlieb** [comment]
Button is fixed. Since there's no real content on this page there's no real value in having a last revised date. It's just a login page for internal CMS users.

**Comment by mmiron-HC** [comment]
Date modified/Version number is a mandatory element in the Canada.ca Content and information Architecture Specifications, therefore it must be there. 
https://design.canada.ca/common-design-patterns/site-footer.html
![image](https://user-images.githubusercontent.com/65728700/130220853-b07638ca-bae0-45cf-bea5-c9d4421a883f.png)

**Comment by davidgotlieb** [comment]
@mmiron-HC I checked with Michael Lawson since this is more a web standards question rather than an accessibility issue. He pointed out that, similar to our internal login page, the AEM login page also doesn't have a version number or last updated date. He thinks it's fine, since there's really no content to change.

**Comment by mmiron-HC** [comment]
@davidgotlieb We are the Web Standards group. I will reach out to Michael to understand why he's giving you this advice when it is clearly marked as a mandatory element. Date modified represents the last time an update was made to the page.

**Comment by mmiron-HC** [comment]
Michael provided additional information.
My thinking was that yes this would be required if it was an external Canada.ca page however the login is internal only and since there is no content on the page that would be updated, that it would not be required.  I was also basing that on the fact that the login for Adobe Experience Manager CMS which is used by Principal Publisher and all departments working with AEM on Canada.ca does not have a date modified or version number. We will close this issue.
